# Generated by Django 4.2.6 on 2023-10-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
